apiVersion: v1
kind: Namespace
metadata:
  name: gpu-test

---
## Request a single AMD GPU via ResourceClaimTemplate and share across containers in the same pod.
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  namespace: gpu-test
  name: single-gpu
spec:
  spec:
    devices:
      requests:
      - name: gpu
        exactly:
          deviceClassName: gpu.amd.com

---
apiVersion: v1
kind: Pod
metadata:
  namespace: gpu-test
  name: pod1
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: docker.io/rocm/pytorch:latest
    command: ["bash", "-c"]
    args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
    resources:
      claims:
      - name: gpu
  - name: ctr1
    image: docker.io/rocm/pytorch:latest
    command: ["bash", "-c"]
    args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
    resources:
      claims:
      - name: gpu
  resourceClaims:
  - name: gpu
    resourceClaimTemplateName: single-gpu
