/*
Copyright (c) Advanced Micro Devices, Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package amdsmi

import (
	"strings"
	"testing"
)

// TestFormatBDF checks the amdsmi_bdf_t bit layout against values produced by
// the C compiler itself. Each raw value below was generated by assigning through
// the real amdsmi_bdf_t bitfields in a C program and printing as_uint, so this
// pins our unpacking to the compiler's actual layout rather than to an assumed
// one. Getting it wrong would not crash: the formatted address simply would not
// match any address discovery found, and Init would fail to bind the GPU.
func TestFormatBDF(t *testing.T) {
	tests := []struct {
		name string
		raw  uint64
		want string
	}{
		{"typical MI300X", 0x0000000000001900, "0000:19:00.0"},
		{"high bus number", 0x000000000000c100, "0000:c1:00.0"},
		{"non-zero domain, max device and function", 0x00000000000105ff, "0001:05:1f.7"},
		{"multi-function device", 0x0000000000003f11, "0000:3f:02.1"},
		{"all zero", 0x0000000000000000, "0000:00:00.0"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := formatBDF(tt.raw); got != tt.want {
				t.Errorf("formatBDF(%#016x) = %q, want %q", tt.raw, got, tt.want)
			}
		})
	}
}

// TestFormatBDFMatchesDiscoveryFormat verifies the rendered address is
// byte-comparable with the sysfs-derived addresses discovery uses as map keys
// (lower-case hex, zero-padded domain and bus).
func TestFormatBDFMatchesDiscoveryFormat(t *testing.T) {
	got := formatBDF(0x000000000000c100)
	if want := "0000:c1:00.0"; got != want {
		t.Fatalf("formatBDF = %q, want %q", got, want)
	}
	for _, r := range got {
		if r >= 'A' && r <= 'F' {
			t.Errorf("formatBDF produced upper-case hex %q; sysfs addresses are lower-case", got)
			break
		}
	}
}

// ---- Tests for the shared partition-set retry loop ----

// TestSetPartitionWithRetry covers the retry policy shared by
// SetComputePartition and SetMemoryPartition. The loop drives real hardware, so
// the C call is injected here to exercise each status path without a GPU.
func TestSetPartitionWithRetry(t *testing.T) {
	// Zero backoff so the retry cases do not actually sleep.
	origBackoff := retryBackoff
	retryBackoff = 0
	defer func() { retryBackoff = origBackoff }()

	tests := []struct {
		name         string
		statuses     []int
		wantErr      bool
		wantAttempts int
		wantErrHas   string
	}{
		{
			name:         "succeeds on first attempt",
			statuses:     []int{statusSuccess},
			wantAttempts: 1,
		},
		{
			name:         "retries while busy then succeeds",
			statuses:     []int{statusBusy, statusBusy, statusSuccess},
			wantAttempts: 3,
		},
		{
			name:         "gives up after retryCount busy responses",
			statuses:     []int{statusBusy, statusBusy, statusBusy, statusBusy},
			wantErr:      true,
			wantAttempts: retryCount + 1,
			wantErrHas:   "with status",
		},
		{
			name:         "setting unavailable fails immediately without retrying",
			statuses:     []int{statusSettingUnavailable, statusSuccess},
			wantErr:      true,
			wantAttempts: 1,
			wantErrHas:   "is not available",
		},
		{
			name:         "an unexpected status is not retried",
			statuses:     []int{99, statusSuccess},
			wantErr:      true,
			wantAttempts: 1,
			wantErrHas:   "with status 99",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			attempts := 0
			err := setPartitionWithRetry(0, "cpx", "compute", "amdsmi_set_gpu_compute_partition", "Set", func() int {
				status := tt.statuses[attempts]
				attempts++
				return status
			})

			if tt.wantErr && err == nil {
				t.Fatal("expected an error, got nil")
			}
			if !tt.wantErr && err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if attempts != tt.wantAttempts {
				t.Errorf("made %d attempts, want %d", attempts, tt.wantAttempts)
			}
			if tt.wantErrHas != "" && !strings.Contains(err.Error(), tt.wantErrHas) {
				t.Errorf("error %q does not contain %q", err, tt.wantErrHas)
			}
		})
	}
}
